package com.freedom.code.model;

import java.util.Date;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.AREA_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.AREA_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.PARENT_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer ison;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.ID
     *
     * @return the value of area.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.ID
     *
     * @param id the value for area.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.AREA_ID
     *
     * @return the value of area.AREA_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.AREA_ID
     *
     * @param areaId the value for area.AREA_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.AREA_NAME
     *
     * @return the value of area.AREA_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.AREA_NAME
     *
     * @param areaName the value for area.AREA_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.PARENT_ID
     *
     * @return the value of area.PARENT_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.PARENT_ID
     *
     * @param parentId the value for area.PARENT_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.ISON
     *
     * @return the value of area.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getIson() {
        return ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.ISON
     *
     * @param ison the value for area.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.CREATE_TIME
     *
     * @return the value of area.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.CREATE_TIME
     *
     * @param createTime the value for area.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.UPDATE_TIME
     *
     * @return the value of area.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.UPDATE_TIME
     *
     * @param updateTime the value for area.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}