package com.freedom.code.model;

import java.util.Date;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITY_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITY_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.PARENT_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer ison;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.ID
     *
     * @return the value of city.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.ID
     *
     * @param id the value for city.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITY_ID
     *
     * @return the value of city.CITY_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITY_ID
     *
     * @param cityId the value for city.CITY_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITY_NAME
     *
     * @return the value of city.CITY_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITY_NAME
     *
     * @param cityName the value for city.CITY_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.PARENT_ID
     *
     * @return the value of city.PARENT_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.PARENT_ID
     *
     * @param parentId the value for city.PARENT_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.ISON
     *
     * @return the value of city.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getIson() {
        return ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.ISON
     *
     * @param ison the value for city.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CREATE_TIME
     *
     * @return the value of city.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CREATE_TIME
     *
     * @param createTime the value for city.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.UPDATE_TIME
     *
     * @return the value of city.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.UPDATE_TIME
     *
     * @param updateTime the value for city.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}