package com.freedom.code.model;

import java.util.Date;

public class EmployeeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.EMPLOYEE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.EMPLOYEE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.LOGIN_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.PASSWORD
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.PHONE
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.EMAIL
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer ison;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.IS_ADMIN
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.BELONG_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String belongId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.ROLE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_info.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.ID
     *
     * @return the value of employee_info.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.ID
     *
     * @param id the value for employee_info.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.EMPLOYEE_ID
     *
     * @return the value of employee_info.EMPLOYEE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.EMPLOYEE_ID
     *
     * @param employeeId the value for employee_info.EMPLOYEE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.EMPLOYEE_NAME
     *
     * @return the value of employee_info.EMPLOYEE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.EMPLOYEE_NAME
     *
     * @param employeeName the value for employee_info.EMPLOYEE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.LOGIN_NAME
     *
     * @return the value of employee_info.LOGIN_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.LOGIN_NAME
     *
     * @param loginName the value for employee_info.LOGIN_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.PASSWORD
     *
     * @return the value of employee_info.PASSWORD
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.PASSWORD
     *
     * @param password the value for employee_info.PASSWORD
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.PHONE
     *
     * @return the value of employee_info.PHONE
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.PHONE
     *
     * @param phone the value for employee_info.PHONE
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.EMAIL
     *
     * @return the value of employee_info.EMAIL
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.EMAIL
     *
     * @param email the value for employee_info.EMAIL
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.ISON
     *
     * @return the value of employee_info.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getIson() {
        return ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.ISON
     *
     * @param ison the value for employee_info.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.IS_ADMIN
     *
     * @return the value of employee_info.IS_ADMIN
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.IS_ADMIN
     *
     * @param isAdmin the value for employee_info.IS_ADMIN
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.BELONG_ID
     *
     * @return the value of employee_info.BELONG_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getBelongId() {
        return belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.BELONG_ID
     *
     * @param belongId the value for employee_info.BELONG_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setBelongId(String belongId) {
        this.belongId = belongId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.ROLE_ID
     *
     * @return the value of employee_info.ROLE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.ROLE_ID
     *
     * @param roleId the value for employee_info.ROLE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.CREATE_TIME
     *
     * @return the value of employee_info.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.CREATE_TIME
     *
     * @param createTime the value for employee_info.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_info.UPDATE_TIME
     *
     * @return the value of employee_info.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_info.UPDATE_TIME
     *
     * @param updateTime the value for employee_info.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}