package com.freedom.code.model;

import java.util.Date;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.PROVINCE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.PROVINCE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer ison;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.ID
     *
     * @return the value of province.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.ID
     *
     * @param id the value for province.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.PROVINCE_ID
     *
     * @return the value of province.PROVINCE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.PROVINCE_ID
     *
     * @param provinceId the value for province.PROVINCE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.PROVINCE_NAME
     *
     * @return the value of province.PROVINCE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.PROVINCE_NAME
     *
     * @param provinceName the value for province.PROVINCE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.ISON
     *
     * @return the value of province.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getIson() {
        return ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.ISON
     *
     * @param ison the value for province.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.CREATE_TIME
     *
     * @return the value of province.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.CREATE_TIME
     *
     * @param createTime the value for province.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.UPDATE_TIME
     *
     * @return the value of province.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.UPDATE_TIME
     *
     * @param updateTime the value for province.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}