package com.freedom.code.model;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ROLE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Integer ison;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.MENU_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ID
     *
     * @return the value of role.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ID
     *
     * @param id the value for role.ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_ID
     *
     * @return the value of role.ROLE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_ID
     *
     * @param roleId the value for role.ROLE_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ROLE_NAME
     *
     * @return the value of role.ROLE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ROLE_NAME
     *
     * @param roleName the value for role.ROLE_NAME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.ISON
     *
     * @return the value of role.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Integer getIson() {
        return ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.ISON
     *
     * @param ison the value for role.ISON
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setIson(Integer ison) {
        this.ison = ison;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.MENU_ID
     *
     * @return the value of role.MENU_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.MENU_ID
     *
     * @param menuId the value for role.MENU_ID
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.CREATE_TIME
     *
     * @return the value of role.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.CREATE_TIME
     *
     * @param createTime the value for role.CREATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.UPDATE_TIME
     *
     * @return the value of role.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.UPDATE_TIME
     *
     * @param updateTime the value for role.UPDATE_TIME
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}