package com.freedom.code.mapper;

import com.freedom.code.model.EmployeeInfo;
import com.freedom.code.model.EmployeeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int countByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int deleteByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int insert(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int insertSelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    List<EmployeeInfo> selectByExample(EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    EmployeeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int updateByExample(@Param("record") EmployeeInfo record, @Param("example") EmployeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int updateByPrimaryKeySelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated Wed May 03 10:44:47 CST 2017
     */
    int updateByPrimaryKey(EmployeeInfo record);
}